### ISSUE TITLE
Latest version does not detect GoogleTest tests.

### ISSUE THREAD

**Issue by vkantchev** [offa/NBCndUnit#3]
Using NetBeans 8.0.2 on Ubuntu 14.04. Unit tests do not show up in the Test Results window.

**Comment by offa** [comment]
Is there a balloontip or notification? You can also open it through _Window -> IDE Tools -> Test Results_ - or by pressing _Alt + Shift + R_.

If this doesn't work, are there any log messages or errors; can you run your tests from commandline?

**Comment by offa** [comment]
I've just released v0.7.0 - the final release for NetBeans 8.1 which is out now. If you are using NB 8.1 please update to this version.

**Comment by offa** [comment]
I'm unable to reproduce, at least without further information. If you have any trouble with the current release, please feel free to reopen or just comment here.
