### ISSUE TITLE
Add support for check/libcheck unit testing framework

### ISSUE THREAD

**Issue by wltjr** [offa/NBCndUnit#50]
This is a feature request for consideration. It maybe beneficial if this project could also support check/libcheck unit testing framework.
https://github.com/libcheck/check/
https://libcheck.github.io/check/

I use your cmake completion, and came across this sometime back. I am slowly integrating check/libcheck into my projects. Thus the interest in integration. If I can help I will, but presently already bit off way more than I can chew, so working on that...

Thank you for consideration of this feature request!

**Comment by offa** [comment]
Thanks for the suggestion. I'll have a look at this.

**Comment by offa** [comment]
I've played around with _LibCheck_ a bit. Unfortunately the verbose output provides much information but the structure makes it difficult to integrate the session state into NetBeans – the current API shipped with NB has some limitations and difficulties here 😞.

Therefore I used the TAP output for some experiments. It doesn't provide all infos but at least the session state is tracked correctly. The "_Go to …_" feature is _not_ implemented yet, as this this another tricky part with _LibCheck_. The implementation is available on the `experimental/issue50-basic_libcheck_support` branch; please tell me, if you need a prebuild NBM.

I'm neither experienced _LibCheck_ nor do I have some realistic tests around, but using the TAP output worked with some basic test suites … at least with some test suites copy & pasted together from the examples .

I used this for the TAP output:

```c
SRunner* sr = srunner_create(s);
// Some more suites added ...
srunner_set_tap(sr, "-");
srunner_run_all(sr, CK_SILENT);
```

**Comment by wltjr** [comment]
Thanks for looking into this, and no worries on perfect integration. I do not need a NBM unless testing in binary snapshot. Even then I can likely copy over any jar I make. I will work on packaging this soon. Though I may need bits that Oracle has not released to Apache yet. If it relies on any of the C/C++ modules, etc. Not sure I can install that stuff via plugin manager either due to other issues with my netbeans package and install. Some of my module versions are off a digit or two, and that causes it to want to upgrade that for some plugins/modules via plugin manager. Otherwise the C/C++ works fine in snapshots. Its just my package that is messed up.

**Comment by wltjr** [comment]
To package for my needs, turns out I do need aspects of Netbeans C/C++ support that Oracle has not released to Apache yet. I did not try live, but at least with 0.7.5. No worries, hopefully that will get released sooner than later.
```
# grep import /tmp/portage/nb-plugins/nbcndunit-0.7.5/temp/build.log
import org.netbeans.modules.cnd.makeproject.api.configurations.ConfigurationDescriptorProvider;
import org.netbeans.modules.cnd.makeproject.api.configurations.Folder;
import org.netbeans.modules.cnd.makeproject.api.configurations.MakeConfigurationDescriptor;
import org.netbeans.modules.cnd.testrunner.spi.TestRecognizerHandler;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactory;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactoryProvider;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactory;
import org.netbeans.modules.cnd.testrunner.spi.TestRecognizerHandler;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactory;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactoryProvider;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactory;
import org.netbeans.modules.cnd.testrunner.spi.TestRecognizerHandler;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactory;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactoryProvider;
import org.netbeans.modules.cnd.testrunner.spi.TestHandlerFactory;
import org.netbeans.modules.cnd.testrunner.spi.TestRecognizerHandler;
import org.netbeans.modules.cnd.api.model.CsmDeclaration;
import org.netbeans.modules.cnd.api.model.CsmFile;
import org.netbeans.modules.cnd.api.model.CsmModelAccessor;
import org.netbeans.modules.cnd.api.model.CsmProject;
import org.netbeans.modules.cnd.modelutil.CsmUtilities;
```

**Comment by offa** [comment]
Frankly speaking, I'm not very happy about the current situation of netbeans. C/C++ is still not supported. With the current uncertain future I don't plan to add support for other frameworks at the moment. Sorry about that.
