### ISSUE TITLE
Parameterized Google Tests report wrong test result

### ISSUE THREAD

**Issue by bed240** [offa/NBCndUnit#6]
Google Test allows for the creation of parameterized tests that will run multiple times across a collection of values provided to the test. The output of these tests are slightly different than normal Google Test output (as seen below). The NBCndUnit plugin fails to correctly parse the output causing the test to show a passing result when it actually fails. Also the test name is not parsed correctly due to the different format under parameterized testing.

Sample parameterized test output:
[----------] 3 tests from X (1 ms total)
[ RUN     ] MyTestTitle/ParamX.Y/0
test.cpp:40: Failure
Value of: false
Actual: false
Expected: true
[  FAILED  ] MyTestTitle/ParamX.Y/0, where GetParam() = 1 (1 ms)
.....

Sample output 2:
[ RUN     ] MyTestTitle/ParamX.Y/0
test.cpp:40: Failure
Value of: false
Actual: false
Expected: true
[  FAILED  ] MyTestTitle/ParamX.Y/0, where GetParam() = 16-byte object <01-00 00-00 00-7F 00-00 0A-00 00-00 00-00 00-00>
......

The existing regular expression breaks down when it hits the ", where GetParam() = " causing the output on the FAILED line not to match.

**Comment by offa** [comment]
Thanks for reporting. I can reproduce the issue and will extends the handler.

**Comment by offa** [comment]
@bed240 I have pushed a fix as branch `issue6`; you alternatively can download the compiled version (_not_ signed yet):

[NBCndUnit-0.7.2-SNAPSHOT.zip](https://github.com/offa/NBCndUnit/files/182920/NBCndUnit-0.7.2-SNAPSHOT.zip)

(sha256: `e874b6efe550a780897c4d430082b127ffc77041cea213af4c0e61a565d35923`)

---

The Test Case I used for testing:

``` cpp
class ParameterTest : public Test, public WithParamInterface<int>
{
protected:
};

constexpr bool test(int x)
{
    return x != 0;
}

TEST_P(ParameterTest, withParameter)
{
    EXPECT_TRUE(test(GetParam()));
}

INSTANTIATE_TEST_CASE_P(withParameterImpl, ParameterTest, ::testing::Values(10, 20, 30, 0));
```

Last value will produce a failure.

Please let me know if it works with your test cases too.

**Comment by bed240** [comment]
Great thanks for the fast reply! I will try to get someone to test this out
tomorrow and will let you know.

Thanks again!

**Comment by bed240** [comment]
Sorry for the delay, we tried the patch and the test output appears to be
correctly parsed so failing test cases correctly show up as failures in the
plugin interface now. Thanks!

One thing to note is if the same TEST_P instance is used in two different
INSTANTIATE_TEST_CASE_P calls, the results will appear duplicated in the
plugin UI. At first the behavior appears similar to issue 4 until I
realized what was causing the "duplicate" results. The full name of a
single test case in your example will be
"withParameterImpl/ParameterTest.withParameter/0".
The plugin uses "ParameterTest" as the test group name and "withParameter"
as the case name and does not use "withParameterImpl". If ParameterTest is
used with another INSTANTIATE_TEST_CASE_P call, a single test case will be
"anotherParameterImpl/ParameterTest.withParameter/0". Again, the test group
name will be "ParameterTest" and the test case name "withParameter",
causing the results from withParameterImpl to appear duplicated under
anotherParameterImpl
results. What is seen in the UI is two identically named Test Groups, the
first with four test cases, the second with eight test cases (four
duplicated from the first group).

To reproduce the issue I think you just have to add the below line:

INSTANTIATE_TEST_CASE_P(anotherParameterImpl, ParameterTest,
::testing::Values(10, 20, 30, 0));

Thanks

**Comment by offa** [comment]
I see …
Adding your line shows the described problem. I'll have a look at it.

Thanks for testing btw.

**Comment by offa** [comment]
@bed240 Here's an updated version (_not signed_):

[NBCndUnit-0.7.2-SNAPSHOT.zip](https://github.com/offa/NBCndUnit/files/196215/NBCndUnit-0.7.2-SNAPSHOT.zip)

(sha256: `9cfbcc8805944e4199b47a2ff596a763b64888a5e49438c3da286ccc00a63e1f`)

---

Instead of `ParameterTest`, the full name (eg. `withParameterImpl/ParameterTest`) is used now in the result window.

So there should be something like this:

```
withParameterImpl/ParameterTest
     - withParameter/0
     - withParameter/1
     - ...
anotherParameterImpl/ParameterTest
     - withParameter/0
     - withParameter/1
     - ...
```

Go to test will work as before.

**Comment by offa** [comment]
@bed240 do you think it's ready so far?

**Comment by offa** [comment]
I assume this issue is _solved_ - if there's any further problem, feel free to re-open.

I'm going to release _v0.7.2_ with the fix included shortly (due the QA verification process it may take some days until it's provided through the NetBeans updater).

Thanks for your contribution @bed240 :+1:
